apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifescope
bases:
  - ../../base
patches:
  - production.yaml
secretGenerator:
  - name: lifescope-embed-prod-config
    files:
      - config.production.js
generatorOptions:
  disableNameSuffixHash: true