apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifescope-location-estimator
  namespace: lifescope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifescope-location-estimator
  template:
    metadata:
      labels:
        app: lifescope-location-estimator
    spec:
      serviceAccountName: lifescope
      containers:
        - name: lifescope-location-estimator
          image: lifescopelabs/lifescope-location-estimator:v1.1.0
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - mountPath: "/usr/src/lifescope-location-estimator/config/tmp"
              name: lifescope-location-estimator-prod-config
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /usr/src/lifescope-location-estimator/config/tmp/production.json /usr/src/lifescope-location-estimator/config/production.json
          imagePullPolicy: IfNotPresent
      dnsPolicy: Default
      volumes:
        - name: lifescope-location-estimator-prod-config
          secret:
            secretName: lifescope-location-estimator-prod-config
      $patch: replace