apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifescope
resources:
  - lifescope-api.yaml
secretGenerator:
  - name: lifescope-api-dev-config
    files:
      - dev.json
generatorOptions:
  disableNameSuffixHash: true