apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifescope
resources:
  - lifescope-location-processor.yaml
secretGenerator:
  - name: lifescope-location-processor-dev-config
    files:
      - dev.json
generatorOptions:
  disableNameSuffixHash: true