apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifescope
resources:
  - lifescope-embed.yaml
secretGenerator:
  - name: lifescope-embed-dev-config
    files:
      - config.dev.js
generatorOptions:
  disableNameSuffixHash: true