apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lifescope
bases:
  - ../../base
patches:
  - production.yaml
secretGenerator:
  - name: lifescope-api-prod-config
    files:
      - production.json
generatorOptions:
  disableNameSuffixHash: true