apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifescope-xr
  namespace: lifescope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifescope-xr
  template:
    metadata:
      labels:
        app: lifescope-xr
    spec:
      serviceAccountName: lifescope
      containers:
        - name: lifescope-xr
          image: lifescopelabs/lifescope-xr:v1.1.1
          ports:
            - containerPort: 3003
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: prod
          volumeMounts:
            - mountPath: "/usr/src/lifescope-xr/config/tmp"
              name: lifescope-xr-prod-config
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /usr/src/lifescope-xr/config/tmp/prod.json /usr/src/lifescope-xr/config/prod.json
          imagePullPolicy: IfNotPresent
      dnsPolicy: Default
      volumes:
        - name: lifescope-xr-prod-config
          secret:
            secretName: lifescope-xr-prod-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-xr-ingress-master
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
    - hosts:
        - xr.lifescope.io
      secretName: lifescope-secret
  rules:
    - host: xr.lifescope.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-nxr-ingress-master
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
    - hosts:
        - nxr.lifescope.io
      secretName: lifescope-secret
  rules:
    - host: nxr.lifescope.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-nxr-ingress-main-minion
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: nxr.lifescope.io
      http:
        paths:
          - backend:
              serviceName: lifescope-nxr
              servicePort: 3004
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lifescope-xr-ingress-main-minion
  namespace: lifescope
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: xr.lifescope.io
      http:
        paths:
          - backend:
              serviceName: lifescope-xr
              servicePort: 3003
            path: /